* Config/Preamble                                                  :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
     (setq org-latex-logfiles-extensions
           (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi"
                   "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
     (add-to-list 'org-latex-classes '("resume" "\\documentclass[10pt]{resume}"))
     (setq org-latex-packages-alist 'nil)

#+END_SRC
#+LATEX_CLASS: resume
#+LATEX_HEADER: \usepackage{ebgaramond}
** Exporter Settings
#+AUTHOR: Alexander Ushanov
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
* CV Header                                                          :ignore:
** Photo & Tagline                                                   :ignore:
#+LATEX_HEADER: \name{Alexander Ushanov}

** Personal Info                                                     :ignore:
#+LATEX_HEADER: \address{github.com/flawless}
#+LATEX_HEADER: \address{quantum-discharge@protonmail.com}
#+LATEX_HEADER: \address{@AlexanderUshanov}
#+LATEX_HEADER: \address{Tbilisi, Georgia}

* Sections                                                           :ignore:
** About                                                             :ignore:
#+begin_export latex
\begin{rSection}{About}

I'm chasing simplicity solving complicted tasks. I believe the key lies is not in writing clean or
performant code, but in predicting whether a specific piece of software will require clear
understanding or performance optimizations, or both.

My journey to this idea has taken me more than ten years in software development, intertwined with
project management, client relationships, and even finding myself in the middle of nowhere
(71°25'43.4"N 151°02'21.7"E) just to deal with a software bug. I've also spent considerable time
organizing groups of people to move in a coherent direction (I started with my own guild in online
games when I was in school).

In the list below, I've kept everything brief to save your time. Please feel free to take a look and
contact me if you share my vision of software development. We will discuss everything in detail.

\end{rSection}
#+end_export
** Experience                                                        :ignore:
#+begin_export latex
\begin{rSection}{Experience}
#+end_export
*** Aceplace                                                         :ignore:
#+begin_export latex
\begin{rSubsection}{Aceplace}{2023 - Present}{Clojure Developer, Lead}{Remote, UAE}
We as a startup trying to bring to life the best in class marketplace for short term yacht and water
experiences rental.
\\
My role in this company as a leader of a small team of skilled engineers is everything about backend
development, operations and internal part of a simple but useful internal UI (Our frontend and app
are mainteined by the second team).

\end{rSubsection}
#+end_export

*** Otus                                                             :ignore:
#+begin_export latex
\begin{rSubsection}{Otus}{2023 - Present}{Clojure Teacher}{Remote, Russia}
Just trying to bring a bit more clojurians for the humanity (:

\end{rSubsection}
#+end_export

*** ARRIVAL                                                          :ignore:
#+begin_export latex
\begin{rSubsection}{ARRIVAL}{2021 - 2023}{Clojure Developer}{Saint Petersburg, Russia -
Tbilisi, Georgia}

Clojure crash course on so called MVP project (we had a couple of prod envs for internal usage and
testing on microfactories prototypes).
\\
Put my hands on a core part of our Service Platform working both on a backend and frontend parts of
the project. Being a member of Architect Committee pushed simplicity and functional design to the
system design ans development process.

\end{rSubsection}
#+end_export

*** Intellect Pro                                                    :ignore:
#+begin_export latex
\begin{rSubsection}{Intellect Pro}{2018 - Present}{Electronic Engineer, Founder}{Saint
Petersburg, Russia}

My hobby electronic project, that somehow turned into production automotive firefighting system (:
\\
Circuit ans PCB design. Embedded development. Project and manufacturing management.

\end{rSubsection}
#+end_export

*** Nonius Engineering                                               :ignore:
#+begin_export latex
\begin{rSubsection}{Nonius Engineering}{2014 - 2021}{Software Developer}{Saint Petersburg,
Russia}

Lead (and most of the time, the only (: ) developer of cloud service written on Python (Flask) for
dredging, mining (not crypto) and marine traffic controll. Developed the service from scratch to
production.

\end{rSubsection}

#+end_export

*** SBS Info                                                         :ignore:
#+begin_export latex
\begin{rSubsection}{SBS Info}{2013 - 2014}{1C Developer}{Saint Petersburg, Russia}

A long time ago, my journey into the world of IT began here.

\end{rSubsection}
#+end_export

*** End of experience section                                        :ignore:
#+begin_export latex
\end{rSection}
#+end_export

** Education                                                         :ignore:
#+begin_export latex
\begin{rSection}{Education}

\begin{rSubsection}{Saint Petersburg State Marine University}{2014}{Specialist degree in Robots
and Robotic systems}{Saint Petersburg, Russia}

Got the knowledge about how to find knowledge.

\end{rSection}

\end{rSection}
#+end_export
