* Config/Preamble                                                  :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
  (setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
  (add-to-list 'org-latex-classes '("resume" "\\documentclass[10pt]{resume}"))
  (setq org-latex-packages-alist 'nil)

#+END_SRC
#+LATEX_CLASS: resume
#+LATEX_HEADER: \usepackage{ebgaramond}
** Exporter Settings
#+AUTHOR: Alexander Ushanov
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
* CV Header                                                          :ignore:
** Photo & Tagline                                                   :ignore:
#+LATEX_HEADER: \name{Alexander Ushanov}

** Personal Info                                                     :ignore:
#+LATEX_HEADER: \address{github.com/Flawless}
#+LATEX_HEADER: \address{alushanov92@gmail.com}
#+LATEX_HEADER: \address{@AlexanderUshanov}
#+LATEX_HEADER: \address{Tbilisi, Georgia}

* Sections                                                           :ignore:
** About                                                             :ignore:
#+begin_export latex
\begin{rSection}{About}

Functional programming fan, I like to work on complex things, researching, developing and watching how my products
operate.
In my work I always look for new ways however try to keep good and proved ones already discovered before. I like to
evolve both professional skills and skills that didn't directly affect my profession life: sports (especially cycling),
languages (I work to become fluent in English), psychology, economy, natural sciences.

Have being organising large amount of people while playing online games in the past, so I know difference between a team
and just a group of people.

As it'll be explained below, I worked both in large teams on big systems and on small projects by my own, have experience
in multiple languages and different paradigms. Right now I'm looking for a team of like-minded people, who share my
thoughts on developing software and my love to a functional way of solving problems.

\end{rSection}
#+end_export
** Experience                                                        :ignore:
#+begin_export latex
\begin{rSection}{Experience}
#+end_export

*** ARRIVAL                                                          :ignore:
#+begin_export latex
\begin{rSubsection}{ARRIVAL}{Jan 2021 - Feb 2023}{Clojure Developer}{Saint Petersburg, Russia - Tbilisi, Georgia}

Completely immersed in Clojure(Script) programming developing Arrival Service Platform core both on the back-end
(Clojure, Datomic) and on the front-end (re-frame + custom ui kit). Worked on architectural problems as a participant of
Architect Committee. Pushed simplicity and functional design to the development process.

\end{rSubsection}
#+end_export

*** Nonius Engineering                                               :ignore:
#+begin_export latex
\begin{rSubsection}{Nonius Engineering}{Jul 2014 - Dec 2020}{Software Developer}{Saint Petersburg, Russia}

Lead (and most of the time, the only (: ) developer of dredging monitoring system written on Python (Flask). Made
fleet management service from scratch to production.

Wrote back-end code on Python and front-end on js and cljs,
maintained CI/CD on GitLab CI (as well as introduced GitLab itself and maintained it),
configured and maintained both cloud (GCP) and real hardware for service deploying,
managed outsource programmers, as the service grew.

\end{rSubsection}

#+end_export

*** Intellect Pro                                                    :ignore:
#+begin_export latex
\begin{rSubsection}{Intellect Pro}{Jan 2018 - Present}{Electronic Engineer, Founder}{Saint Petersburg, Russia}

My hobby electronic project, that somehow turned into production automotive firefighting system (: .

Dived into the world of electronic development: circuit design, PCB design, prototyping, interaction with contractors and
on the one hand low level C programming, a bit of assemble, operation systems under a magnifying glass on the other.

Right now the development is paused. The devices are producing and using by consumers

\end{rSubsection}
#+end_export

*** SBS Info                                                         :ignore:
#+begin_export latex
\begin{rSubsection}{SBS Info}{Jan 2013 - Jan 2014}{1C Developer}{Saint Petersburg, Russia}

Started my career as 1C developer here. Learned many skills (both hard and soft) from my colleagues, interacted directly
with customers and meet their needs as much as I could.

\end{rSubsection}
#+end_export

*** End of experience section                                       :ignore:
#+begin_export latex
\end{rSection}
#+end_export

** Education                                                         :ignore:
#+begin_export latex
\begin{rSection}{Education}

\begin{rSubsection}{Saint Petersburg State Marine University}{July 2014}{Specialist degree in Robots and Robotic systems}{Saint Petersburg, Russia}

Got the knowledge about how to find knowledge.

\end{rSection}

\end{rSection}
#+end_export

** Languages                                                         :ignore:
#+begin_export latex
\begin{rSection}{Languages}

\item Russian - native
\item English - upper intermediate and being learned

\end{rSection}
#+end_export
